name: test

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install Bazelisk
      uses: vsco/bazelisk-action@v1.0.0
      with:
        version: '1.5.0'
        bazel-install-path: '.local/bin'
        os: 'linux'

    - name: Run test
      run: |
        .local/bin/bazel test //test:cpu_timer_test
      env:
        PATH: "${PATH}:.local/bin"
