name: test

on:
  push: {}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install Packages
      run: |
        sudo apt-get update && sudo apt-get install -y clang clang-tidy bazel

    - name: Run test
      run: |
        ${GITHUB_WORKSPACE}/test.sh
